drop table LOG_PAGTO_FUNCIONARIO;
drop table LOG_PAGTO_CLIENTE;
drop table PARTICIPA;
drop table TEM cascade;
drop table TELEFONE_CLIENTE;
drop table CLIENTE;
drop table MODALIDADE;
drop table TELEFONE_FUNCIONARIO;
drop table USUARIO cascade;
drop table SERVIDOR cascade;
drop table INSTRUTOR cascade;
drop table FUNCIONARIO;