CREATE TABLE MODALIDADE(
Nome VARCHAR(30),
CONSTRAINT mod_pk PRIMARY KEY (Nome));

CREATE TABLE CLIENTE(
Matricula VARCHAR(50),
Valor_Mensal INTEGER,
Sexo VARCHAR(1),
Data_Nascimento DATE,
Logradouro VARCHAR(50),
Numero INTEGER,
CPF VARCHAR(11),
Nome VARCHAR(50),
Situacao INTEGER,
CONSTRAINT cli_pk PRIMARY KEY (Matricula));

CREATE TABLE TELEFONE_CLIENTE(
Matricula_Cliente VARCHAR(50),
Telefone VARCHAR(12),
CONSTRAINT tcli_pk PRIMARY KEY (Matricula_Cliente),
CONSTRAINT tcli_fk FOREIGN KEY (Matricula_Cliente) REFERENCES CLIENTE (Matricula));

CREATE TABLE PARTICIPA(
Matricula_Cliente VARCHAR(50),
Nome_Modalidade VARCHAR(30),
CONSTRAINT part_pk PRIMARY KEY (Matricula_Cliente, Nome_Modalidade),
CONSTRAINT part_fk1 FOREIGN KEY (Matricula_Cliente) REFERENCES CLIENTE (Matricula),
CONSTRAINT part_fk2 FOREIGN KEY (Nome_Modalidade) REFERENCES MODALIDADE (Nome));

CREATE TABLE FUNCIONARIO(
CPF VARCHAR(11),
Salario INTEGER,
Turno VARCHAR(15),
Numero INTEGER,
Nome VARCHAR(50),
Situacao INTEGER,
CONSTRAINT func_pk PRIMARY KEY (CPF));

CREATE TABLE TELEFONE_FUNCIONARIO(
CPF_Funcionario VARCHAR(11),
Telefone VARCHAR(12));

CREATE TABLE INSTRUTOR(
CPF VARCHAR(11),
CONSTRAINT func_pk PRIMARY KEY (CPF),
CONSTRAINT func_fk FOREIGN KEY (CPF) REFERENCES FUNCIONARIO (CPF));

CREATE TABLE TEM(
Horario TIMESTAMP,
Nome_Modalidade VARCHAR(30),
CPF_Instrutor VARCHAR(11),
CONSTRAINT tem_pk PRIMARY KEY (Horario, Nome_Modalidade, CPF_Instrutor),
CONSTRAINT tem_fk1 FOREIGN KEY (Nome_Modalidade) REFERENCES MODALIDADE (Nome),
CONSTRAINT tem_fk2 FOREIGN KEY (CPF_Instrutor) REFERENCES INSTRUTOR (CPF));

CREATE TABLE SERVIDOR(
CPF VARCHAR(11),
Cargo VARCHAR(50),
CONSTRAINT serv_pk PRIMARY KEY (CPF),
CONSTRAINT serv_fk FOREIGN KEY (CPF) REFERENCES FUNCIONARIO (CPF));

CREATE TABLE USUARIO(
CPF VARCHAR(11),
Senha VARCHAR(50),
CONSTRAINT user_pk PRIMARY KEY (CPF),
CONSTRAINT user_fk FOREIGN KEY (CPF) REFERENCES SERVIDOR (CPF));

CREATE TABLE LOG_PAGTO_CLIENTE(
Matricula VARCHAR(50),
Data_pagto TIMESTAMP,
Valor_pago INTEGER,
Nome VARCHAR(50),
CONSTRAINT lpc_pk PRIMARY KEY (Matricula,Data_pagto));

CREATE TABLE LOG_PAGTO_FUNCIONARIO(
Data_pagto TIMESTAMP,
Nome VARCHAR(50),
Valor VARCHAR(10),
Salario INTEGER,
CPF VARCHAR(11),
CONSTRAINT lpf_pk PRIMARY KEY (Data_pagto,CPF));

